"""add_intelligence_lineage_audit_models

Revision ID: 4fa8e006b0c0
Revises: '9e76256395b7'
Create Date: 2026-09-09 10:55:38.555103

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '4fa8e006b0c0'
down_revision: Union[str, None] = '9e76256395b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('service_request_id', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_field', sa.String(), nullable=False),
    sa.Column('destination_system', sa.String(), nullable=False),
    sa.Column('destination_field', sa.String(), nullable=False),
    sa.Column('transformation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_lineage_correlation_id'), 'data_lineage', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_data_lineage_id'), 'data_lineage', ['id'], unique=False)
    op.create_index(op.f('ix_data_lineage_service_request_id'), 'data_lineage', ['service_request_id'], unique=False)
    op.create_table('impact_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('old_version', sa.Integer(), nullable=True),
    sa.Column('new_version', sa.Integer(), nullable=False),
    sa.Column('analysis_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_analyses_id'), 'impact_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_impact_analyses_system_name'), 'impact_analyses', ['system_name'], unique=False)
    op.create_table('system_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_schemas_id'), 'system_schemas', ['id'], unique=False)
    op.create_index(op.f('ix_system_schemas_system_name'), 'system_schemas', ['system_name'], unique=False)
    op.create_table('schema_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('is_required', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['system_schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_fields_id'), 'schema_fields', ['id'], unique=False)
    op.create_table('mapping_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_field_id', sa.Integer(), nullable=False),
    sa.Column('target_field', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('mapping_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_field_id'], ['schema_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_suggestions_id'), 'mapping_suggestions', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_suggestions_id'), table_name='mapping_suggestions')
    op.drop_table('mapping_suggestions')
    op.drop_index(op.f('ix_schema_fields_id'), table_name='schema_fields')
    op.drop_table('schema_fields')
    op.drop_index(op.f('ix_system_schemas_system_name'), table_name='system_schemas')
    op.drop_index(op.f('ix_system_schemas_id'), table_name='system_schemas')
    op.drop_table('system_schemas')
    op.drop_index(op.f('ix_impact_analyses_system_name'), table_name='impact_analyses')
    op.drop_index(op.f('ix_impact_analyses_id'), table_name='impact_analyses')
    op.drop_table('impact_analyses')
    op.drop_index(op.f('ix_data_lineage_service_request_id'), table_name='data_lineage')
    op.drop_index(op.f('ix_data_lineage_id'), table_name='data_lineage')
    op.drop_index(op.f('ix_data_lineage_correlation_id'), table_name='data_lineage')
    op.drop_table('data_lineage')
    # ### end Alembic commands ###
