"""Add CitizenConsent and PolicyDecision tables

Revision ID: b888a18ba264
Revises: '31c6ad6c1797'
Create Date: 2026-09-08 23:10:06.897918

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'b888a18ba264'
down_revision: Union[str, None] = '31c6ad6c1797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_consents_citizen_id'), 'citizen_consents', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_citizen_consents_id'), 'citizen_consents', ['id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_citizen_id'), 'policy_decisions', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_correlation_id'), 'policy_decisions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_id'), 'policy_decisions', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_decisions_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_correlation_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_citizen_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_citizen_consents_id'), table_name='citizen_consents')
    op.drop_index(op.f('ix_citizen_consents_citizen_id'), table_name='citizen_consents')
    op.drop_table('citizen_consents')
    # ### end Alembic commands ###
