"""add_workflow_tables

Revision ID: 9e76256395b7
Revises: '65a70042f8f5'
Create Date: 2026-09-08 23:58:30.185554

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9e76256395b7'
down_revision: Union[str, None] = '65a70042f8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_id'), 'workflow_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_name'), 'workflow_definitions', ['name'], unique=True)
    op.create_table('workflow_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('service_request_id', sa.String(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_citizen_id'), 'workflow_instances', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_id'), 'workflow_instances', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_service_request_id'), 'workflow_instances', ['service_request_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_workflow_id'), 'workflow_instances', ['workflow_id'], unique=True)
    op.create_table('workflow_step_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_instance_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_step_instances_id'), 'workflow_step_instances', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_step_instances_workflow_instance_id'), 'workflow_step_instances', ['workflow_instance_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_step_instances_workflow_instance_id'), table_name='workflow_step_instances')
    op.drop_index(op.f('ix_workflow_step_instances_id'), table_name='workflow_step_instances')
    op.drop_table('workflow_step_instances')
    op.drop_index(op.f('ix_workflow_instances_workflow_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_service_request_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_citizen_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_workflow_definitions_name'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
